//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manage_BOM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bom_master
    {
        public string client { get; set; }
        public string setcode { get; set; }
        public string description { get; set; }
        public string version { get; set; }
        public string status { get; set; }
        public string currency { get; set; }
        public Nullable<decimal> standard_cost { get; set; }
        public string maker { get; set; }
        public string last_update { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
