//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manage_BOM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_master
    {
        public long row_id { get; set; }
        public string client { get; set; }
        public string item_no { get; set; }
        public string product_class { get; set; }
        public string description { get; set; }
        public string pallet_config { get; set; }
        public string alternate_code { get; set; }
        public string substitute { get; set; }
        public string billing_group { get; set; }
        public string billing_uom { get; set; }
        public string storage_group { get; set; }
        public string storage_uom { get; set; }
        public string brand { get; set; }
        public string product_group { get; set; }
        public string category { get; set; }
        public string sub_category { get; set; }
        public string sub_category_1 { get; set; }
        public string sub_category_2 { get; set; }
        public string sub_category_3 { get; set; }
        public string sub_category_4 { get; set; }
        public string sub_category_5 { get; set; }
        public string abc_classification { get; set; }
        public string abc_value { get; set; }
        public Nullable<decimal> cycle_count_frequency { get; set; }
        public Nullable<System.DateTime> last_cycle_count { get; set; }
        public Nullable<System.DateTime> last_stocktake { get; set; }
        public string image_filename { get; set; }
        public string dg_flag { get; set; }
        public string un_code { get; set; }
        public string hazchem_code { get; set; }
        public string imo_class { get; set; }
        public string pick_seq { get; set; }
        public string default_grade { get; set; }
        public string status { get; set; }
        public Nullable<decimal> tolerance { get; set; }
        public Nullable<decimal> sample_size { get; set; }
        public Nullable<int> quarantine_day { get; set; }
        public Nullable<decimal> pick_tolerance { get; set; }
        public Nullable<decimal> reorder_level { get; set; }
        public Nullable<decimal> max_stock { get; set; }
        public string currency { get; set; }
        public Nullable<decimal> fob_price { get; set; }
        public Nullable<decimal> landed_price { get; set; }
        public Nullable<decimal> ex_work_price { get; set; }
        public Nullable<decimal> retail_price { get; set; }
        public Nullable<decimal> dealer_price { get; set; }
        public Nullable<decimal> export_price { get; set; }
        public Nullable<int> expiry_prealert { get; set; }
        public Nullable<decimal> shelf_life { get; set; }
        public Nullable<decimal> num_serial { get; set; }
        public string dual_uom { get; set; }
        public string auto_zoning { get; set; }
        public Nullable<decimal> stack_factor { get; set; }
        public string bonded_flag { get; set; }
        public string batch_no { get; set; }
        public string lot_no { get; set; }
        public string expiry_dt { get; set; }
        public string production_dt { get; set; }
        public string item_size { get; set; }
        public string item_color { get; set; }
        public string item_class { get; set; }
        public string weight_required { get; set; }
        public string dimensions { get; set; }
        public string serial_no { get; set; }
        public string supplier { get; set; }
        public string owner { get; set; }
        public string country_origin { get; set; }
        public string nonstandard_pack { get; set; }
        public string others { get; set; }
        public string remarks { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string maker { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<decimal> nesting_factor { get; set; }
        public Nullable<decimal> inventory_holding_factor { get; set; }
        public string hs_code { get; set; }
        public string hs_code_region { get; set; }
        public Nullable<decimal> net_weight { get; set; }
        public string remark2 { get; set; }
        public Nullable<decimal> degree_fr { get; set; }
        public Nullable<decimal> degree_to { get; set; }
        public Nullable<decimal> humidity { get; set; }
        public string ship_packing { get; set; }
        public string healthcare_data { get; set; }
        public string origin_country { get; set; }
        public string item_version { get; set; }
        public string catch_weight_flag { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public string uom_3pl_chrg { get; set; }
        public Nullable<decimal> square_item { get; set; }
        public Nullable<decimal> cubic_item { get; set; }
        public string serial_item { get; set; }
        public Nullable<decimal> min_pick_face { get; set; }
        public Nullable<decimal> max_pick_face { get; set; }
        public Nullable<decimal> unit_cost { get; set; }
        public string packing_uom { get; set; }
        public Nullable<decimal> qty_loose { get; set; }
        public string uom_loose { get; set; }
        public string sap_codeap { get; set; }
        public string sap_codear { get; set; }
        public string check3pl { get; set; }
        public byte[] Picture1 { get; set; }
        public byte[] Picture2 { get; set; }
        public byte[] Picture3 { get; set; }
        public byte[] Picture4 { get; set; }
        public string Primary_Risk { get; set; }
        public string Secondary_Risk { get; set; }
        public string Danger_Type { get; set; }
        public string Allow_Number { get; set; }
        public string Hazardous_Substances_Type { get; set; }
        public string Physical_Type_Of_Chemicals { get; set; }
        public string UN_Number { get; set; }
        public string Packing_Group { get; set; }
        public string UN_Packaging_Code { get; set; }
        public string Ambient_Temperaturn { get; set; }
        public string li_regis_no { get; set; }
        public string li_imported_no { get; set; }
        public string li_dangerous_name { get; set; }
        public Nullable<decimal> li_qty { get; set; }
        public string li_uom { get; set; }
        public string li_pass { get; set; }
        public Nullable<decimal> li_area { get; set; }
        public Nullable<System.DateTime> li_expire_date { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public string cas_no { get; set; }
        public string ratio_des { get; set; }
        public Nullable<decimal> gross_wgt { get; set; }
        public Nullable<decimal> min_qty { get; set; }
        public Nullable<decimal> max_qty { get; set; }
        public string replenish_uom { get; set; }
        public string n_code { get; set; }
    }
}
