//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manage_BOM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_uom
    {
        public long row_id { get; set; }
        public string client { get; set; }
        public string item_no { get; set; }
        public string item_packing { get; set; }
        public string item_uom { get; set; }
        public Nullable<decimal> item_qty { get; set; }
        public Nullable<decimal> item_height { get; set; }
        public Nullable<decimal> item_width { get; set; }
        public Nullable<decimal> item_depth { get; set; }
        public Nullable<decimal> item_volume { get; set; }
        public Nullable<decimal> item_weight { get; set; }
        public Nullable<int> uom_sequence { get; set; }
        public string lowest_uom { get; set; }
        public Nullable<decimal> luom_equivalent { get; set; }
        public Nullable<short> pack_hierarchy { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
